GPU_ID: '-1'
WORKERS: 1
CUDA: False
COMET_PROJECT_NAME: 'local'

TRAIN:
    FLAG: True
    LEARNING_RATE: 0.00005
    BATCH_SIZE: 2
    MAX_EPOCHS: 50
    SNAPSHOT_INTERVAL: 5
    WEIGHT_INIT: "xavier_uniform"
    EALRY_STOPPING: True
    PATIENCE: 5
    CLIP_GRADS: True
    RADAM: False
    # MAX_STEPS: 4

DATASET:
    DATASET: 'clevr'
    DATA_DIR: '/Users/sebamenabar/Documents/datasets/CLEVR/CLEVR_Uni_v1.0/data'
    train_split: 'train'
    params:
        spatial_feats_dset_name: 'data'
        # feats_fname: ''
        # info_fname: 'gqa_objects_gt.json'

model:
    max_step: 4
    separate_syntax_semantics: False
    num_gt_lobs: 1
    common:
        module_dim: 256
    input_unit:
        wordvec_dim: 256
        rnn_dim: 256
        bidirectional: True
        separate_syntax_semantics_embeddings: False
    # control_unit:
    read_unit:
        gate: False
        num_lobs: 0
    write_unit:
        rtom: False
    # output_unit: 