GPU_ID: '-1'
WORKERS: 1
CUDA: False

TRAIN:
    FLAG: True
    LEARNING_RATE: 0.0001
    BATCH_SIZE: 64
    MAX_EPOCHS: 3
    SNAPSHOT_INTERVAL: 5
    WEIGHT_INIT: "xavier_uniform"
    EALRY_STOPPING: True
    PATIENCE: 5
    CLIP_GRADS: True
    RADAM: True
    # MAX_STEPS: 4

DATASET:
    DATA_DIR: '/Users/sebamenabar/Documents/datasets/CLEVR/CLEVR_v1.0/data'

model:
    max_step: 4
    separate_syntax_semantics: True
    common:
        module_dim: 256
    input_unit:
        wordvec_dim: 256
        rnn_dim: 256
        bidirectional: True
        separate_syntax_semantics_embeddings: True
    # control_unit:
    read_unit:
        gate: True
        num_lobs: 10
    write_unit:
        rtom: True
    # output_unit: 