GPU_ID: '-1'
WORKERS: 4
CUDA: False

TRAIN:
    FLAG: True
    LEARNING_RATE: 0.0001
    BATCH_SIZE: 64
    MAX_EPOCHS: 25
    SNAPSHOT_INTERVAL: 5
    WEIGHT_INIT: "xavier_uniform"
    EALRY_STOPPING: True
    PATIENCE: 5
    CLIP_GRADS: True
    MAX_STEPS: 4

DATASET:
    DATA_DIR: '/Users/sebamenabar/Documents/datasets/CLEVR/data'



